name: build & push docker image

on:
  workflow_dispatch:
  push:
    branches: [dev]
    paths:  
      - 'apps/next-app/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Create .env File
      run: |
        touch .env
        echo 'NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}' >> .env
        echo 'NEXT_PUBLIC_GA_TRACKING_ID=${{ secrets.NEXT_PUBLIC_GA_TRACKING_ID }}' >> .env
        echo 'NEXT_PUBLIC_SENTRY_DSN=${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}' >> .env
        echo 'NEXT_PUBLIC_APP_ENV=production' >> .env
      working-directory: ./apps/next-app

    - name: Build and Push Docker Image for ARM64
      uses: docker/build-push-action@v2
      with:
        context: ./next-app
        file: ./next-app/Dockerfile
        push: true
        tags: jamessoun93/feedoong-frontend:latest
        platforms: linux/arm64/v8